// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.BaseManipulator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("position");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_base_manipulators");

                    b.ToTable("base_manipulators", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.IndustrialManipulator", b =>
                {
                    b.HasBaseType("Domain.BaseManipulator");

                    b.Property<int>("WeldsAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("welds_amount");

                    b.ToTable("industrial_manipulators", (string)null);
                });

            modelBuilder.Entity("Domain.ServiceManipulator", b =>
                {
                    b.HasBaseType("Domain.BaseManipulator");

                    b.Property<int>("ServesAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("serves_amount");

                    b.ToTable("service_manipulators", (string)null);
                });

            modelBuilder.Entity("Domain.IndustrialManipulator", b =>
                {
                    b.HasOne("Domain.BaseManipulator", null)
                        .WithOne()
                        .HasForeignKey("Domain.IndustrialManipulator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_industrial_manipulators_base_manipulators_id");
                });

            modelBuilder.Entity("Domain.ServiceManipulator", b =>
                {
                    b.HasOne("Domain.BaseManipulator", null)
                        .WithOne()
                        .HasForeignKey("Domain.ServiceManipulator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_manipulators_base_manipulators_id");
                });
#pragma warning restore 612, 618
        }
    }
}
